# Source: https://hub.docker.com/r/atcommons/mlflow-server
version: '3'

services:
  mlflow:
    build:
      context: mlflow/
      args:
        MLFLOW_VERSION: ${MLFLOW_VERSION}
    ports:
      - "5555:5555"
    environment:
      BACKEND_STORE_URI: sqlite:////mlflow/mlflow.db
    volumes:
      - ./run_env/data:/mlflow