name: Data Pipeline

on:
  push:
    branches: [ ci/cd ]
  pull_request:
    branches: [ ci/cd ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        working-directory: "./code/data_pipeline"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        working-directory: "./code/data_pipeline"
        run: |
          echo "Building data pipeline"
          make build_image
