name: Data Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - "code/data_pipeline/**"
  pull_request:
    branches: [ main ]
    paths:
      - "code/data_pipeline/**"

jobs:
  data_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build image
        working-directory: "./code/data_pipeline"
        run: |
          echo "Building data pipeline.."
          make build_image

      - name: Test data pipeline
        working-directory: "./code/data_pipeline"
        run: |
          echo "Testing data pipeline.."
      
      - name: Deploy data pipeline
        working-directory: "./code/data_pipeline"
        run: |
          echo "Deploying data pipeline.."
          make deploy_dags
