name: Data Pipeline

on:
  push:
    branches: [ ci/cd ]
  pull_request:
    branches: [ ci/cd ]

jobs:
  data_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push image to Docker Hub
        working-directory: "./code/data_pipeline"
        run: |
          echo "Building data pipeline"
          make build_push_image
