name: Monitoring service

on:
    push:
        branches: [ main ]
        paths:
            - "code/monitoring_service/**"
    pull_request:
        branches: [ main ]
        paths:
            - "code/monitoring_service/**"

jobs:
    monitoring_service:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            
            - name: Build image
              working-directory: ".code/monitoring_service"
              run: |
                echo "Building monitoring service"
                make build_image

            - name: Deploy monitoring service
              working-directory: ".code/monitoring_service"
              run: |
                echo "Deploying monitoring service"
                make deploy_dags
